/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/Suit.gltf -o src/Suit.jsx -k 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Suit(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Suit.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions);

  useEffect(() => {
    // The name of the actions is acquired from the console log
    const action = 'Walk'
    // Start the animation with the selected action
    actions[action].play();
    // finish animation
    return () => actions[action]?.fadeOut(0.5);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Suit_Body">
            <skinnedMesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials.Skin} skeleton={nodes.Cube034.skeleton} />
            <skinnedMesh name="Cube034_1" geometry={nodes.Cube034_1.geometry} material={materials.Black} skeleton={nodes.Cube034_1.skeleton} />
            <skinnedMesh name="Cube034_2" geometry={nodes.Cube034_2.geometry} material={materials.White} skeleton={nodes.Cube034_2.skeleton} />
          </group>
          <group name="Suit_Feet">
            <skinnedMesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials.Skin} skeleton={nodes.Cube053.skeleton} />
            <skinnedMesh name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials.Black} skeleton={nodes.Cube053_1.skeleton} />
          </group>
          <group name="Suit_Head">
            <skinnedMesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials.Skin} skeleton={nodes.Cube033.skeleton} />
            <skinnedMesh name="Cube033_1" geometry={nodes.Cube033_1.geometry} material={materials.Hair_Brown} skeleton={nodes.Cube033_1.skeleton} />
            <skinnedMesh name="Cube033_2" geometry={nodes.Cube033_2.geometry} material={materials.Brown} skeleton={nodes.Cube033_2.skeleton} />
            <skinnedMesh name="Cube033_3" geometry={nodes.Cube033_3.geometry} material={materials.Hair_Blond} skeleton={nodes.Cube033_3.skeleton} />
          </group>
          <skinnedMesh name="Suit_Legs" geometry={nodes.Suit_Legs.geometry} material={materials.Black} skeleton={nodes.Suit_Legs.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Suit.gltf')
